[build]
  publish = "_site"
  command = "eleventy"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[template.environment]
  CMS_REPO_PATH = "enter your GitHub repo path here" # e.g github-username/my-github-repo-name
  CMS_REPO_BRANCH = "enter your GitHub repo branch here" # e.g main

# Learn about netlify.toml here: https://www.netlify.com/docs/netlify-toml-reference/